imgsz: 1280
conf_thres: 0.7
iou_thres: 0.45
use_kp_dets: True
conf_thres_kp: 0.5
iou_thres_kp: 0.45
conf_thres_kp_person: 0.2
overwrite_tol: 25
scales: [1]
flips: [-1]
count_fused: False

pose_obj: True  # write pose object labels

nc: 18  # number of classes (person class + 17 keypoint classes)
num_coords: 34  # number of keypoint coordinates (x, y)

# class names
names: [ 'person', 'nose',
         'left_eye', 'right_eye',
         'left_ear', 'right_ear',
         'left_shoulder', 'right_shoulder',
         'left_elbow', 'right_elbow',
         'left_wrist', 'right_wrist',
         'left_hip', 'right_hip',
         'left_knee', 'right_knee',
         'left_ankle', 'right_ankle' ]

kp_bbox: 0.05  # keypoint object size (normalized by longest img dim)
kp_flip: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]  # for left-right keypoint flipping
kp_left: [1, 3, 5, 7, 9, 11, 13, 15]  # left keypoints
kp_face: [0, 1, 2, 3, 4]

kp_names_short:
  0: 'n'
  1: 'ley'
  2: 'rey'
  3: 'lea'
  4: 'rea'
  5: 'ls'
  6: 'rs'
  7: 'lel'
  8: 'rel'
  9: 'lw'
  10: 'rw'
  11: 'lh'
  12: 'rh'
  13: 'lk'
  14: 'rk'
  15: 'la'
  16: 'ra'

# segments for plotting
segments:
  1: [5, 6]
  2: [5, 11]
  3: [11, 12]
  4: [12, 6]
  5: [5, 7]
  6: [7, 9]
  7: [6, 8]
  8: [8, 10]
  9: [11, 13]
  10: [13, 15]
  11: [12, 14]
  12: [14, 16]